eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:9091
          predicates:
            - Path=/api/auth/**
        - id: owner
          uri: http://localhost:9092
          predicates:
            - Path=/api/owner/**
        - id: client
          uri: http://localhost:9093
          predicates:
            - Path=/api/client/**
        - id: employee
          uri: http://localhost:9094
          predicates:
            - Path=/api/employee/**
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service