eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**, /v3/api-docs
          filters:
            - RewritePath=/api/auth(?<segment>/?.*), $\{segment}
        - id: owner
          uri: lb://owner
          predicates:
            - Path=/api/owner/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/api/client/**
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/api/employee/**
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/auth/v3/api-docs
        name: Auth Service
      - url: /api/owner/v3/api-docs
        name: Owner Service
      - url: /api/client/v3/api-docs
        name: Client Service
      - url: /api/employee/v3/api-docs
        name: Employee Service