eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    domain: https://dev-9pn-820c.us.auth0.com
    oauth2:
      client:
        registration:
          auth0:
            client-id: ikWPpY8zw0AkwBUhsKj6rRyqdX2m7Isi
            client-secret: KPrWBYxz754nn-4pJKUnU8DZnmGpPoU-0dCpQg_fr2ysq0AbIw-9NLxoO4cTec-W
            redirect-uri: "{baseUrl}/webjars/swagger-ui/4.15.5/index.html"
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          auth0:
            authorization-uri: ${spring.security.domain}/authorize
            token-uri: ${spring.security.domain}/oauth/token
            user-info-uri: ${spring.security.domain}/userinfo
            jwk-set-uri: ${spring.security.domain}/.well-known/jwks.json
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.domain}/.well-known/jwks.json
springdoc:
  swagger-ui:
    oauth:
      client-id: ikWPpY8zw0AkwBUhsKj6rRyqdX2m7Isi
      client-secret: KPrWBYxz754nn-4pJKUnU8DZnmGpPoU-0dCpQg_fr2ysq0AbIw-9NLxoO4cTec-W