eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: owner
          uri: lb://owner
          predicates:
            - Path=/api/owner/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/api/client/**
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/api/employee/**
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs/auth
        name: Auth Service
      - url: /v3/api-docs/owner
        name: Owner Service
      - url: /v3/api-docs/client
        name: Client Service
      - url: /v3/api-docs/employee
        name: Employee Service