eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: owner
          uri: lb://owner
          predicates:
            - Path=/api/owner/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/api/client/**
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/api/employee/**
springdoc:
  swagger-ui:
    oauth:
      client-id: ikWPpY8zw0AkwBUhsKj6rRyqdX2m7Isi
      client-secret: KPrWBYxz754nn-4pJKUnU8DZnmGpPoU-0dCpQg_fr2ysq0AbIw-9NLxoO4cTec-W
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/auth/v3/api-docs
        name: Auth Service
      - url: /api/owner/v3/api-docs
        name: Owner Service
      - url: /api/client/v3/api-docs
        name: Client Service
      - url: /api/employee/v3/api-docs
        name: Employee Service