eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: owner
          uri: lb://owner
          predicates:
            - Path=/api/owner/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/api/client/**
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/api/employee/**
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/auth/v3/api-docs
        name: Auth Service
      - url: /api/owner/v3/api-docs
        name: Owner Service
      - url: /api/client/v3/api-docs
        name: Client Service
      - url: /api/employee/v3/api-docs
        name: Employee Service