eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: administration
          uri: http://localhost:9091
          predicates:
            - Path=/api/administration/**
        - id: appoitment
          uri: http://localhost:9092
          predicates:
            - Path=/api/appoitment/**
        - id: client
          uri: http://localhost:9093
          predicates:
            - Path=/api/client/**
        - id: store-management
          uri: http://localhost:9094
          predicates:
            - Path=/api/store-management/**
  security:
    domain: https://dev-9pn-820c.us.auth0.com
    oauth2:
      client:
        registration:
          auth0:
            client-id: ikWPpY8zw0AkwBUhsKj6rRyqdX2m7Isi
            client-secret: KPrWBYxz754nn-4pJKUnU8DZnmGpPoU-0dCpQg_fr2ysq0AbIw-9NLxoO4cTec-W
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # La URI de redirección si queremos que auth0 maneje el /auth/token
            redirect-uri: "{baseUrl}/webjars/swagger-ui/4.15.5/index.html" # La URI de redirección si queremos usarlo como api obteniendo el code
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          auth0:
            authorization-uri: ${spring.security.domain}/authorize
            token-uri: ${spring.security.domain}/oauth/token
            user-info-uri: ${spring.security.domain}/userinfo
            jwk-set-uri: ${spring.security.domain}/.well-known/jwks.json
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.domain}/.well-known/jwks.json
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service